//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLySinhVien.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAANzUlEQVR4Xu2de5AcRR3Hf7+evSXhUeasYJLyws70LEQugJBYlLw0JqYsQB5FiQVYKVEEFYuiBETloTwULINKUVhQBYVIUSACvgAFkYeCikJ46pEcOz1zRwjEihBQyeVut9vqsKfHcXf763nt3mz3v/f99XT/vp+bnenpB4ItXZ0B7Ore286DBaDLIbAAWAC6PANd3n17B7AAdHkGurz79g5gAcg3A57nHY2Iv6ReFRFPCILgNqre6swykPsdgHP+FwA4kNpMpdRTYRguo+qtziwDuQLg+/5KpdQDZk0EUEp9LAzD35rGWX3rDOQKAOf8fgD4aOtmvV2hoQnD0DjO9DrdqM8NgGq1ukxKuS5ukhljy2u12pNx423c1BnIDQDO+a0AcEJcI6SUt0ZRdFLceBvXRgBc13UZYzUAcOIa0Wg06o7j+EKI4bh12Lh3ZiCXOwDn/EoAODMFA74v [rest of string was truncated]&quot;;.
        /// </summary>
        public static string asc {
            get {
                return ResourceManager.GetString("asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAODUlEQVR4Xu2de4xdRR3Hf7+5dy+7FkQK2FZK75k5B7ouVGwKRF5aKCqIIETQgBIETUDiK0JQSQWFgMYqBHyAmAhRA0QERcDQyktEIEAFREq73DPnULaURtvwtLvbe2fM6C5st7t7f3Ne93HO/Hu/vzkzv9/nnsc8foNQlFx7AHPd+6LzUACQcwgKAAoAcu6BnHe/uAMUAOTcAznvfnEHKACI7gHXdW/XWh8XvYb0LBljC2u1mp/eFbqj5lh3AM75nYjYlgAg4j6+79e6I0zp9aIAID3fdkTNBQAdEab0GlkAkJ5vO6LmAoCOCFN6jSwASM+3HVFzAUBHhCm9RnYrAPf09vYet2bNmtH0XNcdNccCQAhxDQAcmYYrlFKzGWN72taNiI++8cYbR2/atOlNW9s86mMBkJbD+vv7dx8ZGXkMEYXlNdaOjo4eNjQ0tMXSLrfytgNg6dKl5fXr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
    }
}
